baseURL: "https://blog.cjlio.com"
languageCode: 'zh-cn'
title: 小陈的个人博客
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: ExampleSite
  description: "小陈的个人博客"
  keywords: [Blog, Portfolio, PaperMod]
  author: Me
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "2006-01-02"
  defaultTheme: auto # dark, light
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "favicon.ico"
    favicon16x16: "favicon.ico"
    favicon32x32: "favicon.ico"
    apple_touch_icon: "favicon.ico"
    safari_pinned_tab: "favicon.ico"

  label:
    text: "小陈的个人博客"
    icon: favicon.ico
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: ExampleSite
    subtitle: "This is subtitle"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Post
        url: posts
      - name: Tags
        url: tags
      - name: Archives
        url: archives

  # home-info mode
  homeInfoParams:
    Title: "Hallo Word"
    Content: chenjunlin & blog

  socialIcons:
    - name: github
      url: "https://github.com/chenjunlinabc"
    - name: telegram
      url: "https://t.me/chenjunlinabc"
    - name: email
      url: "mailto:a@cjlio.com"
    - name: twitter
      url: "https://twitter.com/chenjunlina"
    - name: qq
      url: "http://wpa.qq.com/msgrd?v=3&uin=3066887865&site=qq&menu=yes"
    - name: steam
      url: "https://steamcommunity.com/profiles/76561198966883228/"




  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://blog.cjlio.com"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: home
      name: 首页
      url: /
      weight: 1
    - identifier: categories
      name: 分类
      url: /categories/
      weight: 10
    - identifier: archives
      name: 归档
      url: /archives/
      weight: 20
    - identifier: tags
      name: 标签
      url: /tags/
      weight: 30
    - identifier: links
      name: 链接
      url: /links/
      weight: 50
    - identifier: about
      name: 关于
      url: /about/
      weight: 80
    - identifier: search
      name: 搜索
      url: /search/
      weight: 90

outputs:
    home:
        - HTML
        - RSS
        - JSON
